language: node_js
node_js:
  - "8"
before_script:
  - npm install
script:
  - npm run build
  - npm run lint
  - npm run test
  - npm run markdownlint
  # Make sure build output has been committed.
  - git status --porcelain || (echo "Repo is dirty"; git diff; false)
after_success:
  - npm add coveralls
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
cache:
  - npm
